### ISSUE TITLE
群内无法@成员

### ISSUE THREAD

**Issue by xinke2411** [eNkru/electron-wechat#10]
微信群内，没有办法@其他人 这个不太方便，建议加上这个功能

**Comment by eNkru** [comment]
这个微信网页版本的后台没有接口支持，就算能跳出选择。你@的人也不会收到通知。

基本上就和手动@没有区别。

**Comment by xinke2411** [comment]
geek版本的就可以@，是不是可以参考一下，加上这个功能？

**Comment by eNkru** [comment]
他的版本也收不到notification的。只是有跳出联系人列表。你@的人不会知道你有@他

**Comment by xinke2411** [comment]
尴尬了，用了那么久了 一直以为对方能收到@的通知

**Comment by eNkru** [comment]
我是没见到有API支持，朋友试过说不好用。不过我自己没有实验过。

你可以找个朋友试试，好用的话我会想办法加上去。

**Comment by xinke2411** [comment]
试了一下，的确是你说的这样，不会收到通知

**Comment by eNkru** [comment]
哈哈，那么费尽做这个功能也没什么用处啦

**Comment by luobizheng** [comment]
建议加上这个功能，即使对方收不到通知但是至少可以看到这条消息是 指向他的
