### ISSUE TITLE
登录时二维码无法加载

### ISSUE THREAD

**Issue by wanskee** [eNkru/electron-wechat#12]
登录时二维码方框为灰色，没有图案，猜测：可能不是软件本身的问题，可能是网络问题。但是我不知道应该如何去解决，作者可否给些思路，谢谢

**Comment by eNkru** [comment]
应该是你的网络的问题。可能是你用的网络把微信网页版屏蔽了。
你可以试试访问 https://wx.qq.com/ 看看能不能显示二维码。如果也不行的话你看看能不能换一个网络
