### ISSUE TITLE
在ubuntu下面，打开客户端后会显示两个图标

### ISSUE THREAD

**Issue by 460415584** [eNkru/electron-wechat#15]
### 在ubuntu18.04下面，打开客户端后会显示两个图标；
详细：当把安装好的客户端添加到收藏夹（在桌面的收藏栏显示），并且打开客户端后，会出现两个图标，
一个是客户端图标，一个打开后的客户端图标，并且不是微信的，是一个奇怪的图标。
另：客户端的图标的显示比例有点大，和其他的软件并排显示，显得不协调。
图标推荐：https://blog.csdn.net/gatieme/article/details/52800015

关闭后重新打开，不会退出登录，这个做的很棒！在git上其他人做的都没有这个功能。

**Comment by eNkru** [comment]
[这个提交](https://github.com/eNkru/electron-wechat/commit/bc6d24055dc0c744c5c1f4f7b5be46b65be99089) 修正了不显示图标和双图标的问题。你可以自己build一下，或者等一下发布版本。

感谢你的体验和提议，如果还有问题，重开这个ISSUE ：）
