### ISSUE TITLE
话说为啥用chrome网页版无法下载文件(腾讯:我只赚钱,开源界?开发者?不存在的）

### ISSUE THREAD

**Issue by Neutree** [eNkru/electron-wechat#19]
腾讯的开发者大概都不用linux

**Comment by eNkru** [comment]
可以下的，就是大文件的时候要等很久。因为要等整个文件下载完才能弹出保存对话框。
腾讯说微信网页版会被烂用导致了停止更新。而且也没有API给我们做第三方 :(
