### ISSUE TITLE
Ubuntu 18.04.1: dock栏没有微信图标,显示的是一个默认图标

### ISSUE THREAD

**Issue by luo-chuan** [eNkru/electron-wechat#21]
我安装的是deb版本。我不是说顶栏图标，也不是说开始菜单里的图标，而是dock栏图标。

**Comment by eNkru** [comment]
这个是和ELECTRON BUILDER的设置有关，之前做虾米音乐的时候有遇见。等我有时间看看哈。

**Comment by eNkru** [comment]
@luo-chuan 能发个截图吗？还有详细的运行环境？

**Comment by eNkru** [comment]
这个图标的问题比较头疼，不一定哪次升级就坏了。

发现了一个方案， 有空你可以看一下修复了没有。我现在没有在用UBUNTU。

https://github.com/eNkru/electron-wechat/commit/3e166f6dacc7d994b57f422f119568f5277e13f0

如果还有问题的话，重开这个 ：）
