### ISSUE TITLE
登录成功后又到重新登录界面

### ISSUE THREAD

**Issue by MABIY** [eNkru/electron-wechat#23]

**Comment by MABIY** [comment]
操作系统: ubuntu 18.04
uname -a:
Linux lh-Inspiron-3670 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eNkru** [comment]
应该和你的网路或者账号有关，你可以试试官方的web微信可不可以登陆。

https://wx.qq.com/

**Comment by eNkru** [comment]
@MABIY

**Comment by MABIY** [comment]
现在好了　可能时当时的网路问题，谢谢
