### ISSUE TITLE
Ubuntu19 运行无效，请问是否有相关日志可以查看原因？谢谢

### ISSUE THREAD

**Issue by youyiqin** [eNkru/electron-wechat#25]

**Comment by eNkru** [comment]
有截图吗？你可以用COMMAND LINE运行那个AppImage文件。这样有问题的话会在COMMAND LINEL里打印错误信息。

**Comment by cosmt** [comment]
$ electron-wechat 
[1]    6031 segmentation fault (core dumped)  electron-wechat

是这个吗？

**Comment by cosmt** [comment]
我用源码重新编码打包之后 ubuntu19.04 可以使用，
打包用的下边的命令， 先build 然后 deb64
"build": "electron-packager . electron-wechat --platform linux --arch x64 --out dist/",
"deb64": "electron-installer-debian --src dist/electron-wechat-linux-x64/ --dest dist/installers/ --arch amd64",

有问题的可以试下下边这个
链接: https://pan.baidu.com/s/1XWGvZlFhE_HZePULptRQ9w 提取码: c1b1 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by youyiqin** [comment]
重新下载一个就正常了。。。还是谢谢了。
