### ISSUE TITLE
一些关于软件的建议

### ISSUE THREAD

**Issue by qingshuisiyuan** [eNkru/electron-wechat#26]
软件的图标应该要有自己的特色,默认的electron图标不好看
或者作者用了自己的图标但是某些系统不显示？？？

![深度截图_选择区域_20190520154149](https://user-images.githubusercontent.com/48619829/58005857-311e9f00-7b19-11e9-9247-77f7bd2f1e6f.png)

任务栏右键小图标会出现偏移（deepin OS 15.10）

![深度截图_选择区域_20190520154225](https://user-images.githubusercontent.com/48619829/58005898-53182180-7b19-11e9-91b5-fcca3ec48f99.png)

软件顶栏文字可以改为软件名称

![深度截图_选择区域_20190520154409](https://user-images.githubusercontent.com/48619829/58006191-0e40ba80-7b1a-11e9-9cb4-4a89d0c97f49.png)

增加一种“手机模式”，一键改为如图所示的样子（长竖）
![深度截图_选择区域_20190520154542](https://user-images.githubusercontent.com/48619829/58006271-46e09400-7b1a-11e9-978a-2985003d13bc.png)

上图中手动变成长竖界面的话，UI中的联系人名称，以及显示的时间，消息，发送按钮等无法正常的显示
![深度截图_选择区域_20190520154556](https://user-images.githubusercontent.com/48619829/58006480-c53d3600-7b1a-11e9-9ce3-647794eb2ceb.png)
![深度截图_选择区域_20190520161705](https://user-images.githubusercontent.com/48619829/58006483-c53d3600-7b1a-11e9-89ff-ef3cf594aab4.png)

最后感谢作者的辛苦开发，这些建议希望采纳

**Comment by eNkru** [comment]
先标记下。微信网页版用的是非常老的ANGULAR， 不是很好修改。因为不在他们的产品线上，估计他们也不会升级了。

图标和托盘错位的问题应该是DeepIn的的问题，我手上没有这个发行版。你看看能不能发现怎么FIX？欢迎提交PR。

其他UI的建议我先记下了，有时间做一下。

**Comment by eNkru** [comment]
微信，是一个生活方式 -> 特别做了一个操作，哈哈。我可以把这个删掉。我记得默认的是WECHAT还是CHROME来这。。

**Comment by eNkru** [comment]
@qingshuisiyuan 感谢你提的这些想法。有写很有意思。
https://github.com/eNkru/electron-wechat/commit/d9da7758f7e5b0a9c0b3a0824d2c760e961776e8
这个commit应该增加了大部分你需要的功能。

关于图标的问题应该是deepin的UI的不兼容，我没有deepin，暂时没有办法调试。

**Comment by eNkru** [comment]
如果有什么新的想法和建议，欢迎开一个新的帖子讨论
