### ISSUE TITLE
窗口大小无法改变

### ISSUE THREAD

**Issue by j2u** [eNkru/electron-wechat#3]
扫码登录后，微信的窗口还是和扫码登录的窗口大小一样，也无法拉伸窗口
- Ubuntu 16.04
- Unity Desktop

https://drive.google.com/open?id=17pxN9T3wBdBsGvzplc48eSiXzIExZkwt
https://drive.google.com/open?id=1xDoiNSeh-gcAmL2xp0P66nH8_MzliygX

**Comment by eNkru** [comment]
当前判断LOGIN的逻辑有点问题，只有IOS的微信会被识别。

真没想到微信的IOS和ANDROID竟然有不同的逻辑。

看一下能不能有别的方法识别

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-wechat/releases/tag/v0.1.1 @j2u
