### ISSUE TITLE
提示该用户不能使用网页版登录

### ISSUE THREAD

**Issue by mrguozp** [eNkru/electron-wechat#30]
为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录，这种问题怎么解决？
Ubuntu 18

**Comment by eNkru** [comment]
你的微信账号应该是太新了，腾讯不允许登陆网页版。这个是服务器端的限制，我也没有什么好的办法。

你试试从官方的网页登陆应该是同样的提示。
https://wx.qq.com/
