### ISSUE TITLE
下载文件响应慢

### ISSUE THREAD

**Issue by j2u** [eNkru/electron-wechat#5]
下载别人发在群里面的文件的是后响应很慢，尤其是大文件，等了40多m等了大概10秒才弹出保存文件的程序框，文件名是webwxgetmedia。。希望优化下，之前用另geeeek的electron-wechat也是有这个问题的
os:Ubuntu 16.04
Desktop:Unity

**Comment by eNkru** [comment]
你试一下用官方的WEB版本会不会有同样的问题，我估计是因为文件太大导致PRELOAD的时间过长。

如果官方WEB版本也有这个问题就比较好理解了，我有时间看看有没有办法优化。

**Comment by eNkru** [comment]
这个基本上是确定了。微信网页版会先下载好文件才弹出保存窗口。如果下载的文件超大，会导致保存对话框延迟。作为一个网页版的嵌套，这个实在没有什么好的办法解决 ：（
