### ISSUE TITLE
Archlinux+i3wm选中文字后拖动卡死；公众号文章加载不了图片

### ISSUE THREAD

**Issue by Karmenzind** [eNkru/electron-wechat#6]
Archlinux，i3wm

1. 选中文字后拖动卡死。是这样的：
![vokoscreen-2018-06-12_09-25-22](https://user-images.githubusercontent.com/17923071/41265088-0b56db56-6e23-11e8-900c-411e6baa1e63.gif)
然后无论怎样操作，主面板和任务栏图标都没反应，用i3wm的强制退出（Mod+Shift+Q）也无效，只能kill进程
2. 公众号文章加载不了图片，一直在旋转

**Comment by eNkru** [comment]
我没有试过I3WM，不过在GNOME上没有问题。
你可以试试用WEB版本的微信做同样的事情，看能不能卡死。

好奇你做这个干啥，WEB版本没有这个功能，哈哈。

**Comment by eNkru** [comment]
@Karmenzind 
关于公众号文章，我试了一下WEB版也有相同的问题。应该是微信的公众号模板用了IFRAME，最新的CHROME屏蔽了一个关于IFRAME CROSS DOMAIN的问题，导致图片读不出来。

另外一个ELECTRON版本用的是老版ELECTRON，估计是老CHROME就没这个问题。
WORK AROUND是用菜单选择新窗口中打开。

微信团队估计停止了关于WEB版本的更新，我再等等看他们官方会不会修复这个问题。有考虑降级到老版本的ELECTRON。

**Comment by Karmenzind** [comment]
@eNkru 偶然的，就选中后不小心拖动了一下，然后整个不能动了……
Web版和[geek那个版本](https://github.com/geeeeeeeeek/electronic-wechat)都试过了，拖一下就消失了，不会卡
在gnome没问题，那可能就是i3wm的问题了……我试了平铺和floating两种窗口模式，都会卡死
谢谢解答这么详细，IFRAME啥的我都不懂:joy:

**Comment by eNkru** [comment]
待我有时间仔细研究研究

**Comment by Karmenzind** [comment]
谢谢

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-wechat/commit/6e468bc52cb6d0b288c52f00c7c29e7e6759f73c

修复了公众号文章加载不了图片的问题。解决方法是屏蔽了CHROME的WEB SECURITY，允许IFRAME的CROSS DOMAIN访问。

关掉WEB SECURITY就是见仁见智的问题，我们暂且相信微信团队的内容都是安全可靠的吧

@Karmenzind

**Comment by Karmenzind** [comment]
嗯嗯 👍🏿
