### ISSUE TITLE
点击微信信息的url无法跳转

### ISSUE THREAD

**Issue by j2u** [eNkru/electron-wechat#7]
点击之后只是打开了一个tab  url前缀是
https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxcheckurl?requrl=
但是并没有跳转

**Comment by eNkru** [comment]
requrl后面那部分是一个encoded url，这个我也遇到了，还没空出时间去FIX就被你发现了

**Comment by lexusking** [comment]
我也碰到这个问题,微信里面的链接,全部是打不开,我还以为是公司网关禁止了微信链接的跳转.

**Comment by eNkru** [comment]
https://github.com/eNkru/electron-wechat/commit/9a5bbc65cb252ad4e34a6ef63014a6b3b69b7af5

读出正确URL，并跳转. Fixed

@j2u @lexusking
