### ISSUE TITLE
功能介绍太少

### ISSUE THREAD

**Issue by amitbha** [eNkru/electron-wechat#9]
不知道相比官方，提供了哪些好用功能
如果是在 geeeeeeek 的基础上改的，我觉得可以说明一下，这样也知道有哪些功能

**Comment by eNkru** [comment]
谢谢你的关注。

这个是新开的项目，不是基于geek的版本。不过受到了他的启发，基于的也都是微信的web版本。

功能基本都写在了README里，我有一些想法会慢慢的在这个项目里实现。

如果你们有什么好的建议意见我也会考虑。
